name: Run Daily News

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  run-news-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          echo "Dependency installation started at: $(date -u)"
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          echo "Dependency installation ended at: $(date -u)"

      - name: Set up environment
        run: |
          echo "Environment setup started at: $(date -u)"
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env
          echo "NY_API_KEY=${{ secrets.NY_API_KEY }}" >> .env
          echo "NY_API_URL=${{ secrets.NY_API_URL }}" >> .env
          echo "Environment setup ended at: $(date -u)"

      - name: Run script
        run: |
          echo "Script execution started at: $(date -u)"
          python3 src/main.py
          echo "Script execution ended at: $(date -u)"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          echo "Commit and push started at: $(date -u)"
          git config --global user.name "Bu-Du-Dak"
          git config --global user.email "guri930219@gmail.com"
          git add news/
          git commit -m "Update news data at $(TZ=Asia/Seoul date '+%Y-%m-%d %H:%M:%S KST')"
          git push origin main
          echo "Commit and push ended at: $(TZ=Asia/Seoul date '+%Y-%m-%d %H:%M:%S KST')"
