name: Run Daily News

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  run-news-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Set up environment
        run: |
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env
          echo "NY_API_KEY=${{ secrets.NY_API_KEY }}" >> .env
          echo "NY_API_URL=${{ secrets.NY_API_URL }}" >> .env
      - name: run script
        run: python3 src/main.py
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global user.name "Bu-Du-Dak"
          git config --global user.email "guri930219@gmail.com"
          git add news/
          git commit -m "Update news data at $(date -u)"
          git push origin main
