name: Run Daily News

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  run-news-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          echo "Dependency installation started at: $(date -u)"
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          echo "Dependency installation ended at: $(date -u)"

      - name: Set up environment
        run: |
          echo "Environment setup started at: $(date -u)"
          echo "GNEWS_API_KEY=${{ secrets.GNEWS_API_KEY }}" >> .env
          echo "GNEWS_API_URL=${{ secrets.GLOBAL_API_URL }}" >> .env
          echo "PAT=${{ secrets.PAT }}" >> .env
          echo "Environment setup ended at: $(date -u)"

      - name: Run script
        run: |
          echo "Script execution started at: $(date -u)"
          python3 src/main.py
          echo "Script execution ended at: $(date -u)"
